CREATE DATABASE IF NOT EXISTS SCHEDULE;

USE SCHEDULE;

CREATE TABLE SCHEDULE
(
    ID       BIGINT       AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    NAME    VARCHAR(100) NOT NULL COMMENT '작성자명',
    TITLE VARCHAR(100) NOT NULL COMMENT '제목' ,
    PW VARCHAR(100) NOT NULL COMMENT '비밀번호',
    CONTENTS TEXT NOT NULL COMMENT '내용',
    IS_DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부(0:활성, 1: 삭제)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

